#!/bin/bash

# ----------------------------------------------------------------------
# AlternC - Web Hosting System
# Copyright (C) 2000-2012 by the AlternC Development Team.
# https://alternc.org/
# ----------------------------------------------------------------------
# LICENSE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License (GPL)
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# To read the license please visit http://www.gnu.org/copyleft/gpl.html
# ----------------------------------------------------------------------
# Purpose of file: Install roundcube conf files.
# ----------------------------------------------------------------------

if [ "$1" = "upgrade" ]
then
    echo "Upgrading AlternC-mailman"
    /usr/share/alternc/install/upgrade_mailman_check.sh
    echo "Overwriting mailman binaries"
    ARCH=$(dpkg --print-architecture)
    if [ "$ARCH" = "amd64" ]
    then
	install -o root -g list -m 2755  /usr/share/alternc/alternc-mailman/amd64/* /usr/lib/cgi-bin/mailman/
    else
        if [ "$ARCH" = "i386" ]
	then
	    install -o root -g list -m 2755  /usr/share/alternc/alternc-mailman/i386/* /usr/lib/cgi-bin/mailman/
	else
	    echo "****************************************************************************"
	    echo "WARNING: ARCH is $ARCH, which is neither amd64 nor i386, please read"
	    echo "mailman-itk-fix/README.txt in alternc-mailman source to build your binaries"
	    echo "mailman will likely NOT WORK in apache-mpm-itk in the meantime ..."
	    echo "****************************************************************************"
	fi
    fi
fi  


