#!/bin/bash

# ----------------------------------------------------------------------
# AlternC - Web Hosting System
# Copyright (C) 2000-2012 by the AlternC Development Team.
# https://alternc.org/
# ----------------------------------------------------------------------
# LICENSE
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License (GPL)
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# To read the license please visit http://www.gnu.org/copyleft/gpl.html
# ----------------------------------------------------------------------
# Purpose of file: Install mailman conf files.
# ----------------------------------------------------------------------

if [ "$1" = "upgrade" ]
then
    echo "Upgrading AlternC-mailman"
    /usr/share/alternc/install/upgrade_mailman_check.sh

    echo "ensuring apache2 symlink is setup in /etc/apache2/conf.d/"
    # compatibility with both Apache 2.2 and 2.4 makes it Wheezy AND Jessie-compliant : 
    if [ -d "/etc/apache2/conf.d" ]
	then
	ln -sf /etc/mailman/apache.conf /etc/apache2/conf.d/mailman.conf 
    fi
    if [ -d "/etc/apache2/conf-enabled" ]
	then
	ln -sf /etc/mailman/apache.conf /etc/apache2/conf-enabled/mailman.conf 
    fi

fi  


