#!/bin/sh -e

. /usr/share/debconf/confmodule

CONFIGFILE="/etc/alternc/local.sh"
MAILMAN_CONFIG="/etc/mailman/mm_cfg.py"
MAILMAN_CONFIG_TEMPLATE="/etc/alternc/templates/mailman/mm_cfg.py"
MAILMAN_CONFIG_BACKUP="/var/lib/alternc/backups/etc-mailman-mm_cfg.py"
MAILMAN_PASS="`perl -e 'print map{("a".."z","A".."Z",0..9)[int(rand(62))]}(1..10)' `" # copy-pasted from alternc/debian/config

# new packages put binaries in /usr/lib/mailman/bin
if [ -d /usr/lib/mailman/bin ]
then
    MAILMAN_BIN="/usr/lib/mailman/bin"
else
    MAILMAN_BIN="/var/lib/mailman/bin"
fi

case "$1" in
  configure)
    . "$CONFIGFILE"

    # Then, configure the quota for "mailman"
    /usr/lib/alternc/quota_init mailman 0 

    echo "Installing mysql table"
    mysql --defaults-file=/etc/alternc/my.cnf < /usr/share/alternc/install/mailman.sql
    
    # Install generated mailman configuration if it has not been modified since
    # last package configuration
    if [ -f "$MAILMAN_CONFIG_BACKUP" ]; then
        if ! diff -q "$MAILMAN_CONFIG" "$MAILMAN_CONFIG_BACKUP"; then
            echo "$MAILMAN_CONFIG has been modified since last alternc-mailman"
            echo "configuration.  You should merge your changes to"
            echo "$MAILMAN_CONFIG_TEMPLATE and delete $MAILMAN_CONFIG_BACKUP"
            exit 1
        fi
    fi
    sed -e "s/%%fqdn%%/$FQDN/" < "$MAILMAN_CONFIG_TEMPLATE" > "$MAILMAN_CONFIG"
    cp -a -f "$MAILMAN_CONFIG" "$MAILMAN_CONFIG_BACKUP"

    MAILMAN_VERSION=`dpkg -l mailman | grep ^ii | awk '{print $3}' | sed -e s/-.*// -e 's/[^:]*://'`
    echo "detected mailman version $MAILMAN_VERSION"
    if [ -d "/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.d" ] ; then
      PATCHDIR="/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.d"
    else
      PATCHDIR=""
      PATCHFILE="/usr/share/alternc-mailman/patches/mailman-true-virtual-$MAILMAN_VERSION.patch"
    fi
    PATCH_MARKER="/usr/share/alternc-mailman/patches/mailman-true-virtual.applied"
    if [ -h $PATCH_MARKER ]; then
        PATCH_VERSION=`readlink $PATCH_MARKER | sed -e 's/^.*-//;s/\.patch$//;s/\.d$//'`
        echo "mailman patch detected, version $PATCH_VERSION"
        if [ "$PATCH_VERSION" = "$MAILMAN_VERSION" ]; then
            echo "mailman already patched, will not patch again"
        else
            echo "wrong version of the patch, we assume that mailman was upgraded"
            rm -f $PATCH_MARKER
        fi
    fi
    if [ "$PATCHDIR" = "" ] ; then
        if [ ! -r $PATCHFILE ]; then
            echo "no patchfile for mailman $MAILMAN_VERSION"
        fi
    fi
    if [ -r "$PATCHFILE" -o  "$PATCHDIR" != "" ] ; then if [ ! -h $PATCH_MARKER ]; then
        db_get alternc-mailman/patch-mailman || true
        if [ "$RET" = "true" ]; then
            if [ "$PATCHDIR" != "" ] ; then # we have multiple files
            {
                cd /        # patches should be relative to root, now
                patch_ok="yes"
                for pfile in $PATCHDIR/* ; do
                    if patch --dry-run -p0 < $pfile; then
                        echo "applying patch $pfile :"
                        if patch -p0 < $pfile; then
                            echo "patch applied sucessfully"
                        else
                            patch_ok="no"
                            echo "cannot apply patch, your mailman is probably broken now, aborting"
                            false
                        fi
                    else
                        echo "patch will not apply cleanly, aborting"
                        patch_ok="no"
                    fi
                    if [ "$patch_ok" = "yes" ] ; then
                        # this will tell alternc-mailman the patch was applied successfully
                        ln -fs $PATCHDIR $PATCH_MARKER
                        invoke-rc.d mailman restart || true
                    fi
                done
            }
            else # old fashion unique patch file
            {
                cd /var/lib
                echo "testing the patch"
                if patch --dry-run -p0 < $PATCHFILE; then
                    echo "applying patch"
                    if patch -p0 < $PATCHFILE; then
                        echo "patch applied sucessfully"
                        # this will tell alternc-mailman the patch was applied successfully
                        ln -fs $PATCHFILE $PATCH_MARKER
                        invoke-rc.d mailman restart || true
                    else
                        echo "cannot apply patch, your mailman is probably broken now, aborting"
                        false
                    fi
                else
                    echo "patch will not apply cleanly, aborting"
                fi
            }
            fi ; fi
        else
            echo "not applying virtual mailman patch"
        fi
    fi
    # tell debconf to go away, otherwise alternc.install will freeze
    db_stop

    # Create the "mailman" list if it does not exist yet
    if [ ! -d /var/lib/mailman/lists/mailman ]; then
        # Create the list :
	owner='admin@'${FQDN} 
        su - list -c "/usr/lib/mailman/bin/newlist -q \"mailman\" \"$owner\" \"${MAILMAN_PASS}\""
        if [ "$?" -eq "0" ]
        then
            mysql --defaults-file=/etc/alternc/my.cnf -Bse "INSERT INTO mailman SET uid=2000, list='mailman', name='mailman', domain='${FQDN}', password='${MAILMAN_PASS}', mailman_result='', mailman_action='OK', owner='$owner';"
        else
	    mysql --defaults-file=/etc/alternc/my.cnf -Bse "INSERT INTO mailman SET uid=2000, list='mailman', name='mailman', domain='${FQDN}', password='${MAILMAN_PASS}', mailman_result='A fatal error happened when creating the list', mailman_action='OK', owner='$owner';"
        fi
    fi

    # Create default quota "mailman" with value 0
    mysql --defaults-file=/etc/alternc/my.cnf -Bse "INSERT INTO defquotas VALUES ('mailman', 0, 'default')" || true

    echo "installing required apache modules" 
    a2enmod rewrite
    a2enmod proxy
    a2enmod proxy_http

    # make the mailman.localdomain goes to local apache2 ;) 
    if ! grep -q "127.0.0.1.*mailman.localdomain" /etc/hosts
    then 
	echo "adding mailman.localdomain to /etc/hosts"
	echo "" >>/etc/hosts
	echo "127.0.0.1  mailman.localdomain" >>/etc/hosts
    fi

    echo "checking for upgrades"
    /usr/share/alternc/install/upgrade_mailman_check.sh $2

    echo "**********************************************"
    echo "*            ALTERNC-MAILMAN                 *"
    echo "* Please run alternc.install to fully deploy *"
    echo "* Then change your quota to activate Mailman *"
    echo "**********************************************"
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.
#DEBHELPER#

# vim: et sw=4
